"""Initial schemas: accelerometers, sensor_types

Revision ID: bfd7348f81a8
Revises: 
Create Date: 2025-12-29 23:26:27.517940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd7348f81a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accelerometers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sensor_type_id', sa.Uuid(), nullable=False),
    sa.Column('generate_data_params', sa.JSON(), nullable=False),
    sa.Column('anomalous_data_params', sa.JSON(), nullable=True),
    sa.Column('stream_state', sa.JSON(), nullable=True),
    sa.Column('create_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_type_id'], ['sensor_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accelerometers')
    op.drop_table('sensor_types')
    # ### end Alembic commands ###
