"""Added system ops related fields (create,update,archive)

Revision ID: d998f7819d06
Revises: bfd7348f81a8
Create Date: 2025-12-30 21:51:04.100072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd998f7819d06'
down_revision: Union[str, Sequence[str], None] = 'bfd7348f81a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accelerometers', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('accelerometers', sa.Column('archived_ts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sensor_types', sa.Column('create_ts', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sensor_types', sa.Column('update_ts', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sensor_types', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('sensor_types', sa.Column('archived_ts', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_types', 'archived_ts')
    op.drop_column('sensor_types', 'archived')
    op.drop_column('sensor_types', 'update_ts')
    op.drop_column('sensor_types', 'create_ts')
    op.drop_column('accelerometers', 'archived_ts')
    op.drop_column('accelerometers', 'archived')
    # ### end Alembic commands ###
